### ISSUE TITLE
not multiprocess compatible

### ISSUE THREAD

**Issue by helppe** [roger21/imagezoomuglyfixes#1]
hello,
this is not multiprocess compatible?

**Comment by roger21** [comment]
yes this has already been stated and even if i haven't tested it myself, i totally believe it

as stated in the add-on page, this is a lazy fix that does not try to improve the original code of the add-on, the multiprocess incompatibility being inherent to the original code of the add-on, this will not be fix

**Comment by helppe** [comment]
do you know a similar addon to replace with?
i 've not found equivalent one
