### ISSUE TITLE
rotate function doesn't work anymore

### ISSUE THREAD

**Issue by helppe** [roger21/imagezoomuglyfixes#2]
hi,
we can't rotate images anymore :(

**Comment by roger21** [comment]
thank you for your reports and sorry for the delay, indeed nothing works anymore

it seems to be caused by a late refactoring that was not followed by comprehensive tests

i published a version 0.1.1 that should fix those 3 issues (awaiting for review)

**Comment by helppe** [comment]
the images are note cropped on top when zoomed anymore, but they are still cropped on top when we use the "fit width" option.

thanks for your work and happy new year :D

[edit] in fact it is not so annoying, since we can zoom/unzoom and the top of image reappear.
so in fact it is good anyway[/edit]

**Comment by roger21** [comment]
i close those 3 ones as fixed even though your last comment, just to close something, i'll open a new something when i get time to check it :p
